"""empty message

Revision ID: 362e2cb783da
Revises: 0e14d2bda772
Create Date: 2023-04-01 20:26:59.943879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362e2cb783da'
down_revision = '0e14d2bda772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_type')

    # ### end Alembic commands ###
