"""empty message

Revision ID: 561813a17eb8
Revises: 39f8265ae81d
Create Date: 2023-03-31 18:09:28.402844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561813a17eb8'
down_revision = '39f8265ae81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
