"""empty message

Revision ID: 5a94915c9ac2
Revises: 4e26943521dd
Create Date: 2023-05-07 16:43:23.456051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a94915c9ac2'
down_revision = '4e26943521dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('auth_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('timetamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_timetamp'), ['timetamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_timetamp'))

    op.drop_table('posts')
    # ### end Alembic commands ###
