"""empty message

Revision ID: d97085dfca93
Revises: cda0ea1c9f80
Create Date: 2023-03-19 21:58:45.162688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97085dfca93'
down_revision = 'cda0ea1c9f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['user_phone'])
        batch_op.create_unique_constraint(None, ['user_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_phone',
               existing_type=sa.String(length=300),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
